version: '3.8'

services:
  #  app:
  #    image: my-spring-boot-app
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - db
  mysql:
    image: mysql:latest
    container_name: full-stack-ecommerce
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
